# Generated by Django 5.2.4 on 2025-08-02 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='videos',
            name='views',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
