# Generated by Django 5.2.4 on 2025-08-18 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0003_alter_videos_views_videoview'),
    ]

    operations = [
        migrations.CreateModel(
            name='Audios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('Audio', models.FileField(blank=True, null=True, upload_to='Audios')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
