# Generated by Django 5.2.4 on 2025-08-18 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0004_audios'),
    ]

    operations = [
        migrations.AddField(
            model_name='audios',
            name='artist',
            field=models.CharField(default='joel', max_length=100),
            preserve_default=False,
        ),
    ]
